DROP SCHEMA IF EXISTS scollective;
CREATE SCHEMA scollective;
USE scollective;

-- User table 
-- id_user SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT, 
CREATE TABLE USER_INFO (
    user_name VARCHAR(50) NOT NULL,
    user_password VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    age SMALLINT UNSIGNED NOT NULL,
    user_register DATETIME,
    PRIMARY KEY (user_name )
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Player types table
CREATE TABLE PLAYER_TYPES (
	id_ptypes SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name_ptypes VARCHAR(50) NOT NULL,
    life_points SMALLINT UNSIGNED NOT NULL, 
    speed SMALLINT UNSIGNED NOT NULL, 
    PRIMARY KEY (id_ptypes)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Life table 
CREATE TABLE LIFE (
	id_life SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    life_points SMALLINT NOT NULL,
    life_stamp TIMESTAMP NOT NULL,
    PRIMARY KEY (id_life)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Gadget table
CREATE TABLE GADGET (
	id_gadget SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    gadget_name VARCHAR(50) NOT NULL,
    gadget_description VARCHAR(200) NOT NULL,
    player_type SMALLINT UNSIGNED NOT NULL, 
    PRIMARY KEY (id_gadget),
	CONSTRAINT `fk_GADGET_PLAYERTYPE` FOREIGN KEY (player_type) REFERENCES PLAYER_TYPES(id_ptypes) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Player table
CREATE TABLE PLAYER (
	id_player SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT, 
    last_connection TIMESTAMP NOT NULL, 
    user_name VARCHAR(50) NOT NULL,
    player_type SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY (id_player), 
    CONSTRAINT `fk_PLAYER_USERINFO` FOREIGN KEY (user_name) REFERENCES USER_INFO(user_name) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_PLAYER_PLAYERTYPES` FOREIGN KEY (player_type) REFERENCES PLAYER_TYPES(id_ptypes) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Progress table 
CREATE TABLE PROGRESS (
	id_progress SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    level_achieved SMALLINT UNSIGNED NOT NULL,
    user_name VARCHAR(50) NOT NULL,
    player_type SMALLINT UNSIGNED NOT NULL,
    life_points SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY (id_progress), 
    CONSTRAINT `fk_PROGRESS_USERINFO` FOREIGN KEY (user_name) REFERENCES USER_INFO(user_name) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_PROGRESS_PLAYERTYPES` FOREIGN KEY (player_type) REFERENCES PLAYER_TYPES(id_ptypes) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_PROGRESS_LIFE` FOREIGN KEY (life_points) REFERENCES LIFE(id_life) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Wins table 
CREATE TABLE WINS (
	id_wins SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_name VARCHAR(50) NOT NULL,
    player_type SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY (id_wins), 
    CONSTRAINT `fk_WINS_USERINFO` FOREIGN KEY (user_name) REFERENCES USER_INFO(user_name) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT `fk_WINS_PLAYERTYPES` FOREIGN KEY (player_type) REFERENCES PLAYER_TYPES(id_ptypes) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE VIEW MOST_WINS AS 
SELECT user_name AS user_wins, player_type FROM WINS
INNER JOIN PLAYER_TYPES ON WINS.player_type = PLAYER_TYPES.id_ptypes

